language: java

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

jdk:
  - oraclejdk8

before_install: chmod +x gradlew
before_deploy: chmod +x upload_build
deploy: ./upload_build