#!/bin/bash
echo "Initializing Upload.."
WARN=0
if [[ $COMMIT_MSG == *\[D\]* ]]
then
    java -jar uploader.jar $DEV_KEY $DEV_DEPLOY
else
    WARN=$((WARN++))
fi

if [[ $COMMIT_MSG == *\[R\]* ]]
then
    java -jar uploader.jar $PROD_KEY $PROD_DEPLOY
else
    WARN=$((WARN++))
fi

if [ $WARN -eq 2 ]
then
    echo "Build discarded."
fi
echo "End of Script."