#!/bin/bash
cd ./build/libs/

#Gambiarra do Tipo Malandra
find . -type f ! -name '*-all.jar' -delete

FILE_NAME=`echo Miyuki-*`
WARN=0
if [[ $COMMIT_MSG == *\[D\]* ]]
then
    echo "Uploading ./$FILE_NAME to VPS Relay [DEBUG]..."
    v=`curl -X POST -F compiledJar="@./$FILE_NAME" $DEV_DEPLOY`
    echo -e "\n$v\n"
else
    WARN=$((WARN++))
fi

if [[ $COMMIT_MSG == *\[R\]* ]]
then
    echo "Uploading ./$FILE_NAME to VPS Relay [RELEASE]..."
    v=`curl -X POST -F compiledJar="@./$FILE_NAME" $PROD_DEPLOY`
    echo -e "\n$v\n"
else
    WARN=$((WARN++))
fi

if [ $WARN -eq 2 ]
then
    echo "Build discarded."
fi
