#!/bin/bash

# PRs? NOPE.
if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then exit 0; fi

COMMIT_MSG="$(git log --format=%B -n 1 $TRAVIS_COMMIT | grep .)"
WARN=0
if [[ $COMMIT_MSG == *\[D\]* ]]
then
    java -jar uploader.jar $DEV_KEY $DEV_DEPLOY
else
    WARN=$((WARN++))
fi

if [[ $COMMIT_MSG == *\[R\]* ]]
then
    java -jar uploader.jar $PROD_KEY $PROD_DEPLOY
else
    WARN=$((WARN++))
fi

if [ $WARN -eq 2 ]
then
    echo "Build discarded."
fi